### ISSUE TITLE
parse math

### ISSUE THREAD

**Issue by whaaaley** [jamen/pull-css#1]
Math is reduced to a single value when possible. When it can't be reduced then `calc()` is used.

in

```
.foo {
  width: 50% + 2px;
  margin: 1px + 2px;
}
```

out

```
.foo {
  width: calc(50% + 2px);
  margin: 3px;
}
```

Some basic functions may be useful too. Possibly mirroring the Math methods in JavaScript.

**Comment by jamen** [comment]
Module uses `css` internally which doesn't parse any values, I think I'll keep it simplistic like that.  Closing.
